miketheo423/Homebrew_Heroes

- back-end/config/routes.js
- back-end/controllers/beer.js
- back-end/package-lock.json
- back-end/package.json
- back-end/server.js
- back-end/test/api_routes_spec.js
Test with `cd backend && mocha` 
(seed database first to pass index and show routes)
Available routes:
1) **GET `/api/beers`** - index / beer feed
Responds with ALL beers in database from newest to oldest.
Only includes the fields required for the beer preview cards.
Response:
```
{beers: [
{
name: 'beer name',
photoUrl: "http://www.image.com/image.jpg",
style: "IPA",
id: #,
user: {
username: "user name",
id: #
}
},
{. . .}
]}
```
2) **GET `/api/beers/:id`** - show / beer detail page
Respond with the full details of a single beer
Response:
```
{
id: #,
photoUrl: "imageUrl",
name: "Beer Name,
style: "Beer Style",
abv: "#",
ibus: "#",
description: "Description",
recipe: "Recipie",
createdAt: "2017-11-10T04:33:35.225Z",
updatedAt: "2017-11-10T04:33:35.225Z",
userId: #,
user: {
id: #, …
```
> Backend api beer routes

- back-end/db/seed.js
- back-end/server.js
- front-end/src/app/app.module.ts
- front-end/src/app/beer-feed-page/beer-feed-page.component.html
- front-end/src/app/beer-feed-page/beer-feed-page.component.ts
- front-end/src/app/beer-feed-page/beer-feed.service.spec.ts
- front-end/src/app/beer-feed-page/beer-feed.service.ts
Add a service to the beer feed to call the api for all the beer previews
ALSO.... Updated **CORS** in `server.js` on the backend
> Add Beer-Feed-Service and call GET route for beer feed

- back-end/config/routes.js
Correct the path for `GET '*/'` route.
> Fix bad route

- front-end/src/app/beer-feed-page/beer-feed-page.component.css
- front-end/src/app/beer-feed-page/beer-feed-page.component.html
Added route for beer.id through routerLink (the plus signs on cards)
Redid responsive design to better fit cards
> adding responsive and route for beer.id

- back-end/config/routes.js
- back-end/controllers/users.js
- front-end/src/app/beers/beers.module.ts
- front-end/src/app/beers/beers.service.spec.ts
- front-end/src/app/beers/beers.service.ts
1) **`GET /api/users`** - User index route for searching users
Responds with an array of all users and their `usersname`, `photoUrl`, and `id`.
2) **`GET /api/users/:id`** - User show route for user profiles
Responds with the relevant user information and an array of their beers:
```
{
username: "username",
createdAt: "2017-11-10T23:23:12.192Z",
updatedAt: "2017-11-10T23:23:12.192Z",
firstName: "first",
lastName: "last",
photoUrl: "url",
beers: [
{
name: "name",
photoUrl: "url",
style: "style",
id: #
},
{ ... }
]
}
```
3) **`PUT /api/users/`** - Edit a user's profile information
Pass the informatin to be updated in the request `body`. 
The updates will be applied to the ***currently logged in user***. (user Id not needed)
Responds with a success message.
Added `beers.service.ts` and …
> User API Routes & Beer Service

- front-end/src/app/login-modal/login-modal.component.css
- front-end/src/app/login-modal/login-modal.component.html
Removers modal header and footer and adds some padding to modal body
> Cleans up modal

- front-end/src/app/app.component.css
- front-end/src/app/app.component.html
- front-end/src/app/footer/footer.component.css
- front-end/src/app/header/header.component.css
- front-end/src/app/header/header.component.html
Makes header always stay on top of page.
Makes footer stick to bottom of page
> Makes a fixed header and a sticky footer

- front-end/src/app/app.component.html
- front-end/src/app/app.component.ts
Fixes public router bug and adds if statement for header fix
> Sticky footer

- front-end/src/app/beer-feed-page/beer-feed-page.component.css
- front-end/src/app/header/header.component.css
adding responsive queries to header for all pages
> added responsive queries to header

- back-end/config/routes.js
- back-end/controllers/beer.js
- back-end/server.js
- front-end/src/app/beers/beers-new/beers-new.component.ts
- front-end/src/app/beers/beers.service.ts
Fix issue with credentials.
Add userId to beers when they get created.
> Freakin credentials

- front-end/src/app/beers/beers-edit/beers-edit.component.css
- front-end/src/app/beers/beers-edit/beers-edit.component.html
- front-end/src/app/beers/beers-edit/beers-edit.component.ts
- front-end/src/app/beers/beers-new/beers-new.component.css
- front-end/src/app/beers/beers-new/beers-new.component.ts
- front-end/src/app/beers/beers-show/beers-show.component.html
Adds margin to forms for better spacing
Adds working edit form
Adds brewer name to brewer show page
> Beer edit page

- back-end/controllers/users.js
- front-end/src/app/app-routing.module.ts
- front-end/src/app/app.module.ts
- front-end/src/app/beer-feed-page/beer-feed-page.component.ts
- front-end/src/app/footer/footer.component.css
- front-end/src/app/footer/footer.component.html
- front-end/src/app/header/header.component.css
- front-end/src/app/users/users-show/users-show.component.css
- front-end/src/app/users/users-show/users-show.component.html
- front-end/src/app/users/users-show/users-show.component.ts
- front-end/src/app/users/users-show/users-show.service.ts
- front-end/src/app/users/users.module.ts
added full functionality to user-show/responsive as well
> adding all the user-page info and routing

- back-end/config/routes.js
- back-end/controllers/beer.js
- back-end/db/seed.js
- front-end/src/app/app.module.ts
- front-end/src/app/beer-feed-page/beer-feed-page.component.html
- front-end/src/app/beer-feed-page/beer-feed-page.component.ts
- front-end/src/app/beer-feed-page/beer-feed.service.ts
- front-end/src/app/beers/beers-edit/beers-edit.component.html
- front-end/src/app/beers/beers-new/beers-new.component.html
- front-end/src/app/beers/beers-new/beers-new.component.ts
- front-end/src/app/beers/beers.service.ts
- front-end/src/app/header/header.component.html
Assigns a photo based on the style choses in the new beer form.
Lets users search beers with use of a dropdown menu.
> Search functionality

- back-end/controllers/auth.js
- front-end/src/app/current-user.service.ts
- front-end/src/app/login-modal/login-modal.component.html
- front-end/src/app/login-modal/login-modal.component.ts
Refactor the login and signup form to use angular forms.
Refactor the backend auth login and signup routes with custom callbacks instead of redirects.
> login and logout in the currentuserservice

- back-end/controllers/beer.js
- back-end/controllers/users.js
Add conditionals to controllers to make sure current userId matches the IDs of the rows being updated
> Check update/delete authorization on backend

- front-end/src/app/users/users-show/users-show.component.css
- front-end/src/app/users/users-show/users-show.component.html
- front-end/src/app/users/users-show/users-show.component.ts
- front-end/src/app/users/users.module.ts
added + routerlink, also added edit button
> added edit button, added +

- back-end/db/seed.js
- front-end/src/app/beer-feed-page/beer-feed-page.component.html
- front-end/src/app/beers/beers-edit/beers-edit.component.html
- front-end/src/app/beers/beers-new/beers-new.component.html
- front-end/src/app/header/header.component.css
Adds more seed beers and users.
Removes photoURL option from both new and edit beer forms.
Fixes z-index of navbar.
> Adding seeds

- back-end/config/routes.js
- back-end/controllers/users.js
- back-end/db/seed.js
- front-end/src/app/app.module.ts
- front-end/src/app/users/users-edit/users-edit.component.css
- front-end/src/app/users/users-edit/users-edit.component.html
- front-end/src/app/users/users-edit/users-edit.component.ts
- front-end/src/app/users/users-show/users-show.component.html
- front-end/src/app/users/users-show/users-show.component.ts
- front-end/src/app/users/users.module.ts
- front-end/src/app/users/users.service.ts
added edit functionality/modal
> adding edit functionality

- front-end/src/app/users/users-show/users-show.component.css
- front-end/src/app/users/users-show/users-show.component.html
Added button for adding beers on user page
> added button for adding beers

- back-end/config/passport.js
- front-end/src/app/users/users-show/users-show.component.css
added new photo url to passport and added a little top margin in user-edit/css
> added picture to passport

- front-end/src/app/users/users-show/users-show.component.html
- front-end/src/app/users/users-show/users-show.component.ts
Add conditional to show **EDIT** and **NEW** buttons on own user's profile or **MESSAGE HERO** on other user's profile.
> Add conditional to user profile

- front-end/src/app/beers/beers-show/beers-show.component.css
- front-end/src/app/beers/beers-show/beers-show.component.html
Adds link to brewer page on each beer-show page.
> Adds a link to the brewers page on each beer show page

- front-end/src/app/beers/beers-show/beers-show.component.css
- front-end/src/app/beers/beers-show/beers-show.component.html
- front-end/src/app/footer/footer.component.css
- front-end/src/app/header/header.component.css
- front-end/src/app/landing-page/landing-page.component.css
- front-end/src/app/users/users-edit/users-edit.component.html
- front-end/src/app/users/users-show/users-show.component.css
- front-end/src/app/users/users-show/users-show.component.html
adding css stuff around the page
> adding css stuff around the page

- back-end/db/seed.js
- front-end/src/app/beers/beers-new/beers-new.component.ts
- front-end/src/app/header/header.component.css
- front-end/src/app/header/header.component.html
added new sour picture and nav-bar-functionality
> added nav bar links and changed sour pic

- front-end/src/app/beers/beers-show/beers-show.component.css
- front-end/src/app/header/header.component.html
Fixes mobile link not working bug with a z-index change on div it is located in.
Fixes the header naves so that logout is on the right and beer-feed is on the left.
> Link working and header nav links switched

- front-end/src/app/app.component.spec.ts
- front-end/src/app/auth.guard.spec.ts
- front-end/src/app/beer-feed-page/beer-feed-page.component.spec.ts
- front-end/src/app/beer-feed-page/beer-feed-page.component.ts
- front-end/src/app/beer-feed-page/beer-feed.service.spec.ts
- front-end/src/app/beers/beers-edit/beers-edit.component.spec.ts
- front-end/src/app/beers/beers-new/beers-new.component.spec.ts
- front-end/src/app/beers/beers-show/beers-show.component.spec.ts
- front-end/src/app/beers/beers.service.spec.ts
- front-end/src/app/current-user.service.spec.ts
- front-end/src/app/footer/footer.component.spec.ts
- front-end/src/app/header/header.component.spec.ts
- front-end/src/app/landing-page/landing-page.component.spec.ts
- front-end/src/app/login-modal/login-modal.component.spec.ts
- front-end/src/app/users/users-edit/users-edit.component.spec.ts
- front-end/src/app/users/users-show/users-show.component.spec.ts
- front-end/src/index.html
Closes #66 
* Comment out excess unit tests.
* Pass app component build tests
* Write and pass 2 feed page unit tests
> Passing 5 of 5 unit tests
